# This workflow automates the versioning and release process for the npm package
# using semantic-release. It also creates a versioned Git tag.

name: Release and Publish npm Package

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      - name: Setup Buf, Go, and Node.js
        uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies and plugins
        run: |
          npm install
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest

      - name: Generate and Prepare Package
        run: |
          export PATH="$PATH:$(pwd)/node_modules/.bin"
          buf generate
          mkdir -p gen/ts/real # Ensure the target directory exists
          # Copy all files from the source directory to the destination
          if [ -d "src/ts" ]; then
            cp -r src/ts/* gen/ts/real/
          fi
          node ./scripts/create-ts-index.js # <--- ADD THIS LINE
          cp npm/package.json gen/ts/
          cp npm/README.md gen/ts/

      - name: Run semantic-release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}