# This workflow automates the versioning and release process for the npm package
# using semantic-release. It also creates a versioned Git tag.

name: Release and Publish npm Package

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      - name: Setup Buf, Go, and Node.js
        uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          cache: false
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies and plugins
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          npm install --prefix ./npm

      - name: Generate and Prepare Package
        run: |
          export PATH="$PATH:$(go env GOPATH)/bin:$(pwd)/npm/node_modules/.bin"
          echo "--- Starting package preparation (Merged Hierarchy) ---"
          
          # 1. CLEANUP: Ensure a clean slate.
          echo "Cleaning up old generated directories..."
          rm -rf gen/ts gen/go
          
          # 2. GENERATE: Outputs hierarchical .ts files to gen/ts/
          buf generate 
          
          # 3. COPY HELPER FILES: Selectively copy only non-test .ts files.
          echo "Merging mirrored TypeScript files into gen/ts/ hierarchy..."
          # ✅ CORRECTED COMMAND: Use rsync to copy ONLY non-test .ts files
          rsync -avm --include='*.ts' --exclude='*.test.ts' --include='*/' --exclude='*' src/ts/ gen/ts/proto/
          
          # 4. Create index file
          echo "Creating the main index.ts barrel file..."
          node ./scripts/create-ts-index.js 
          
          # ... (rest of the script is the same) ...
          
          echo "--- START: index.ts Content Debug ---"
          cat gen/ts/index.ts
          echo "--- END: index.ts Content Debug ---"

          echo "--- START: Directory Structure Debug ---"
          find gen/ts -type f 
          echo "--- END: Directory Structure Debug ---"
          
          cp npm/package.json gen/ts/
          cp npm/README.md gen/ts/
          cp npm/tsconfig.json gen/ts/
          
          echo "--- ✅ Package preparation complete ---"

      - name: Install Build Dependencies
        working-directory: ./gen/ts
        run: npm install

      - name: Build TypeScript to JavaScript
        working-directory: ./gen/ts
        run: npm run build

      - name: Verify Package Structure
        working-directory: ./npm
        run: ./node_modules/.bin/vitest run --reporter verbose

      - name: Publish to npm and create Git tag
        run: npx semantic-release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}