name: Publish Go Module

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository at the specific tag
        uses: actions/checkout@v4
        with:
          path: main
          ref: ${{ github.ref }}

      - name: Checkout Go module repository
        uses: actions/checkout@v4
        with:
          repository: illmade-knight/go-action-intention-protos
          path: go-protos
          token: ${{ secrets.GH_PAT }}

      - name: Setup Buf and Go
        uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          cache: true

      - name: Install protoc-gen-go
        run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest

      - name: Clean Go module directory
        working-directory: ./go-protos
        # Remove any previously generated files to prevent old artifacts from being committed.
        run: rm -rf ./gen ./proto

      - name: Generate Go code
        working-directory: ./main
        run: |
          buf generate --template buf.gen.go.yaml --output ../go-protos

      - name: Update Go Module Dependencies
        working-directory: ./go-protos
        run: go mod tidy

      - name: Commit and push Go module changes
        working-directory: ./go-protos
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "chore(release): update generated Go modules for ${{ github.ref_name }}" || exit 0
          git push

      - name: Tag Go module repository
        working-directory: ./go-protos
        run: |
          git tag ${{ github.ref_name }}
          git push origin ${{ github.ref_name }}