# This GitHub Actions workflow automates the generation and publication of
# both the TypeScript (npm) and Go (GitHub) packages from the Protobuf definitions.

name: Generate and Publish Packages

on:
  # Trigger the workflow on every push to the main branch.
  push:
    branches:
      - main

jobs:
  # --- Job 1: Build & Generate ---
  # This job is the single source of truth for code generation. It installs all
  # dependencies, runs the generator, and uploads the results as artifacts.
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4

      - name: Setup Buf
        uses: bufbuild/buf-setup-action@v1

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # THE FIX: Install the protoc plugins that buf needs.
      - name: Install Go plugins
        run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest

      - name: Install Node.js dependencies (which includes protoc-gen-es)
        run: npm install

      - name: Generate all code
        run: npm run generate

      # Upload the generated code so the publish jobs can use it.
      - name: Upload TS artifact
        uses: actions/upload-artifact@v4
        with:
          name: ts-protos
          path: gen/ts/

      - name: Upload Go artifact
        uses: actions/upload-artifact@v4
        with:
          name: go-protos
          path: gen/go/

  # --- Job 2: Publish the TypeScript package to npm ---
  publish-npm:
    runs-on: ubuntu-latest
    # This job will only run after the 'build' job succeeds.
    needs: build
    steps:
      - name: Setup Node.js for publishing
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      # Download the pre-generated TypeScript code from the build job.
      - name: Download TS artifact
        uses: actions/download-artifact@v4
        with:
          name: ts-protos

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  # --- Job 3: Publish the Go module to its dedicated GitHub repository ---
  publish-go:
    runs-on: ubuntu-latest
    # This job will only run after the 'build' job succeeds.
    needs: build
    steps:
      - name: Checkout Go module repository
        uses: actions/checkout@v4
        with:
          repository: illmage-knight/go-action-intention-protos
          token: ${{ secrets.GH_PAT }}

      # Download the pre-generated Go code and place it in the checked-out repo.
      - name: Download Go artifact
        uses: actions/download-artifact@v4
        with:
          name: go-protos
          path: .

      - name: Commit and push Go module
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          # The `|| exit 0` ensures the step doesn't fail if there are no changes.
          git commit -m "chore: update generated Go modules" || exit 0
          git push

