# This workflow is triggered ONLY when a new version tag (e.g., v1.0.1) is pushed
# by another workflow (like the npm release workflow).
# Its sole job is to generate and publish the Go module for that specific version.

name: Publish Go Module

on:
  push:
    tags:
      - 'v*' # Trigger on tags like v1.0.0, v1.2.3, etc.

jobs:
  publish-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository at the specific tag
        uses: actions/checkout@v4
        with:
          path: main
          ref: ${{ github.ref }} # Checkout the tag that triggered the workflow

      - name: Checkout Go module repository
        uses: actions/checkout@v4
        with:
          repository: illmade-knight/go-action-intention-protos
          path: go-protos
          token: ${{ secrets.GH_PAT }}

      - name: Setup Buf and Go
        uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-go@v4
        with: { go-version: '1.24' }

      # --- Generate and Prepare Package ---
      # This step generates the Go code and places it directly into the correct repo path.
      - name: Generate Go code
        working-directory: ./main
        run: |
          buf generate --template buf.gen.go.yaml --output ../go-protos

      # This step updates the Go module dependencies, which is good.
      - name: Update Go Module Dependencies
        working-directory: ./go-protos
        run: go mod tidy

      # Commit and push changes
      - name: Commit and push Go module changes
        working-directory: ./go-protos
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "chore(release): update generated Go modules for ${{ github.ref_name }}" || exit 0
          git push